### ISSUE TITLE
Tried v1.5.1 - Still getting the same import issue

### ISSUE THREAD

**Issue by Greyhart42** [jbhaywood/5e-statblock-importer#32]
I must be doing something wrong. I tried to reply to the email, but it bounced due to size.

I downloaded and unzipped v1.5.1, then copied it into my Modules directory. I deleted the old module directory and renamed the new one 5e-statblock-importer (basically removed the -1.5.1 at the end) I started Foundry and it shows v1.5.1

![image](https://user-images.githubusercontent.com/47504205/184676084-afa60add-295c-4aab-98eb-0ac2da7139f2.png)

I imported the Goblin Assassin:

_Goblin Assassin
Small Humanoid (Goblin), Any Alignment
Armor Class 15 (studded leather armor)
Hit Points 16 (3d6 + 6)
Speed 30 ft., climb 20 ft.
STR DEX CON INT WIS CHA
8 (−1) 16 (+3) 14 (+2) 10 (+0) 10 (+0) 8 (−1)
Skills Stealth +7
Senses darkvision 60 ft., passive Perception 10
Languages Common, Goblin
Proficiency Bonus +2
Backstab. When the assassin has advantage on their attack roll
against a creature that isn’t a Construct or Undead, their attacks
deal an extra 1d6 damage and inflict a bleeding wound on the target
that lasts until the bleeding creature regains at least 1 hit point.
A bleeding creature loses 2 hit points for each bleeding wound
they have at the start of their turn. Any creature can use an action
to staunch all a target’s wounds, ending the effect.
Crafty. The assassin doesn’t provoke opportunity attacks when
they move out of an enemy’s reach.
ACTIONS
Scimitar. Melee Weapon Attack: +5 to hit, reach 5 ft., one target.
Hit: 6 (1d6 + 3) slashing damage.
Dagger. Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or
range 20/60 ft., one target. Hit: 5 (1d4 + 3) piercing damage.
Summon Shadows (1/Day). A 10-foot-radius sphere of magical
darkness emanates from a point the assassin can see for 1 minute.
The assassin can see in this magical darkness. At the start of their
turn, the assassin can move the darkness up to 30 feet to a point
they can see. If the assassin takes damage, the effect ends.
BONUS ACTIONS
Sneak. The assassin takes the Hide action._

I got the same problem as before:
![image](https://user-images.githubusercontent.com/47504205/184676390-851e75d4-5758-4876-94c1-fb701cb97719.png)

It doesn't seem to parse the second language correctly, putting it along with everything after the Proficiency Bonus and before ACTIONS into the Special (Split with Semi-Colon) field.
This particular Monster doesn't have a saving throw, so I also imported the Goblin Boss who, as you pointed out, has Saves, not Saving Throw. I got the same result as the Goblin Assassin.

I deleted the Goblin Boss actor and changed Saves to Saving Throw, then re-imported it. That didn't change anything.

I originally thought I must have made a mistake updating the module, but it shows correctly as v1.5.1 in Manage Modules, so I have no idea what is wrong.

Sorry for the problems,

**Comment by jbhaywood** [comment]
My bad. This is fixed in v1.5.3. Thanks for the detailed info. It really helps.

**Comment by Greyhart42** [comment]
I’ve been a programmer for over 40 years. I’m pretty good at testing. 😊

We’re getting closer. I still see some issues. I’ll send another report.

Ken
